name: example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <3.9.9"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  forui: ^0.9.1+1

  flutter_bamboo_ui_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.14.3

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/

  fonts:
    - family: monserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/png/Logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true