name: flutter_bamboo_ui_kit
description: "A custom widget made from TLab for TLab."
version: 0.0.1
homepage: https://tlab.co.id/
repository:

#publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  syncfusion_flutter_charts: ^28.2.4
  persistent_bottom_nav_bar_v2: ^5.3.1
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  assets:
    - assets/svg/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/inter.ttf
